version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: conference_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@postgres:5432/conference_db"
      SECRET_KEY: "your-production-secret-key-change-this"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://138.124.14.215:8000/api
      - REACT_APP_WS_URL=ws://138.124.14.215:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: